#!/usr/bin/env python3

import os, sys
import time
from argparse  import ArgumentParser
from threading import Thread

sys.path.append("{}/supervisors/".format(sys.path[0]))
sys.path.append("{}/common/".format(sys.path[0]))
sys.path.append("{}/Vision/".format(sys.path[0]))

from server import Server
from cube_detector import * 
from anchor import *

    

def server(args):

    srv = Server()
    srv.start()

    


parser = ArgumentParser()
subparsers = parser.add_subparsers()


server_parser = subparsers.add_parser('server')
server_parser.set_defaults(func=server)


args = parser.parse_args()
args.func(args)


