BOARD = esp32
CHIP = esp32

#Arduino file
SKETCH = ./main.ino

BOARD_UUID = esp32
COMMON = ../common
#Setup all libs used !
LIBS = 


# Congratulations! You made a pretty Makefile :)
# Now let the grown-ups do the hard work :D
MODULEMK_DIR = ..
include $(MODULEMK_DIR)/Module.mk

